//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WRMC.Infrastructure.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ContextResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ContextResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WRMC.Infrastructure.Localization.ContextResources", typeof(ContextResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConnectionString.
        /// </summary>
        public static string Client_ConnectionString {
            get {
                return ResourceManager.GetString("Client.ConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Client_Description {
            get {
                return ResourceManager.GetString("Client.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expire Date.
        /// </summary>
        public static string Client_ExpireDate {
            get {
                return ResourceManager.GetString("Client.ExpireDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Client_Name {
            get {
                return ResourceManager.GetString("Client.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ValidUpto.
        /// </summary>
        public static string Client_ValidUpto {
            get {
                return ResourceManager.GetString("Client.ValidUpto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read DateTime.
        /// </summary>
        public static string SensorHistory_ReadDateTime {
            get {
                return ResourceManager.GetString("SensorHistory.ReadDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read Index.
        /// </summary>
        public static string SensorHistory_ReadIndex {
            get {
                return ResourceManager.GetString("SensorHistory.ReadIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string SensorHistory_Value {
            get {
                return ResourceManager.GetString("SensorHistory.Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string SiloItem_Address {
            get {
                return ResourceManager.GetString("SiloItem.Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Box.
        /// </summary>
        public static string SiloItem_Box {
            get {
                return ResourceManager.GetString("SiloItem.Box", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to False value count.
        /// </summary>
        public static string SiloItem_FalseValueCount {
            get {
                return ResourceManager.GetString("SiloItem.FalseValueCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Histories.
        /// </summary>
        public static string SiloItem_Histories {
            get {
                return ResourceManager.GetString("SiloItem.Histories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index.
        /// </summary>
        public static string SiloItem_Index {
            get {
                return ResourceManager.GetString("SiloItem.Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line.
        /// </summary>
        public static string SiloItem_Line {
            get {
                return ResourceManager.GetString("SiloItem.Line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mapping Info.
        /// </summary>
        public static string SiloItem_MappingInfo {
            get {
                return ResourceManager.GetString("SiloItem.MappingInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string SiloItem_Name {
            get {
                return ResourceManager.GetString("SiloItem.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offset.
        /// </summary>
        public static string SiloItem_Offset {
            get {
                return ResourceManager.GetString("SiloItem.Offset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset false value counter.
        /// </summary>
        public static string SiloItem_ResetFalseValueCounter {
            get {
                return ResourceManager.GetString("SiloItem.ResetFalseValueCounter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rom.
        /// </summary>
        public static string SiloItem_Rom {
            get {
                return ResourceManager.GetString("SiloItem.Rom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Culture.
        /// </summary>
        public static string User_Culture {
            get {
                return ResourceManager.GetString("User.Culture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Mode.
        /// </summary>
        public static string User_DarkMode {
            get {
                return ResourceManager.GetString("User.DarkMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string User_Description {
            get {
                return ResourceManager.GetString("User.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string User_Email {
            get {
                return ResourceManager.GetString("User.Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string User_FirstName {
            get {
                return ResourceManager.GetString("User.FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        public static string User_FullName {
            get {
                return ResourceManager.GetString("User.FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Id.
        /// </summary>
        public static string User_Id {
            get {
                return ResourceManager.GetString("User.Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string User_Image {
            get {
                return ResourceManager.GetString("User.Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string User_LastName {
            get {
                return ResourceManager.GetString("User.LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string User_Password {
            get {
                return ResourceManager.GetString("User.Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Confirmation.
        /// </summary>
        public static string User_PasswordConfirmation {
            get {
                return ResourceManager.GetString("User.PasswordConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string User_PhoneNumber {
            get {
                return ResourceManager.GetString("User.PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right to left.
        /// </summary>
        public static string User_RightToLeft {
            get {
                return ResourceManager.GetString("User.RightToLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        public static string User_Roles {
            get {
                return ResourceManager.GetString("User.Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Provider.
        /// </summary>
        public static string UserSession_LoginProvider {
            get {
                return ResourceManager.GetString("UserSession.LoginProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string UserSession_Name {
            get {
                return ResourceManager.GetString("UserSession.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider Name.
        /// </summary>
        public static string UserSession_ProviderName {
            get {
                return ResourceManager.GetString("UserSession.ProviderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        public static string UserSession_StartDate {
            get {
                return ResourceManager.GetString("UserSession.StartDate", resourceCulture);
            }
        }
    }
}
