//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WRMC.Infrastructure.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DisplayResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DisplayResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WRMC.Infrastructure.Localization.DisplayResources", typeof(DisplayResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth.
        /// </summary>
        public static string Birth {
            get {
                return ResourceManager.GetString("Birth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of birth.
        /// </summary>
        public static string BirthDate {
            get {
                return ResourceManager.GetString("BirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection String.
        /// </summary>
        public static string ConnectionString {
            get {
                return ResourceManager.GetString("ConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Password.
        /// </summary>
        public static string CurrentPassword {
            get {
                return ResourceManager.GetString("CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employer.
        /// </summary>
        public static string DemographicIntake_Employer {
            get {
                return ResourceManager.GetString("DemographicIntake_Employer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employment Status.
        /// </summary>
        public static string DemographicIntake_EmploymentStatus {
            get {
                return ResourceManager.GetString("DemographicIntake_EmploymentStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Financial Support Source.
        /// </summary>
        public static string DemographicIntake_FinancialSupportSource {
            get {
                return ResourceManager.GetString("DemographicIntake_FinancialSupportSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Immigration Status.
        /// </summary>
        public static string DemographicIntake_ImmigrationStatus {
            get {
                return ResourceManager.GetString("DemographicIntake_ImmigrationStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Household Income.
        /// </summary>
        public static string DemographicIntake_Income {
            get {
                return ResourceManager.GetString("DemographicIntake_Income", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insurance Name.
        /// </summary>
        public static string DemographicIntake_InsuranceName {
            get {
                return ResourceManager.GetString("DemographicIntake_InsuranceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insurance Number.
        /// </summary>
        public static string DemographicIntake_InsuranceNumber {
            get {
                return ResourceManager.GetString("DemographicIntake_InsuranceNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Grade.
        /// </summary>
        public static string DemographicIntake_LastGrade {
            get {
                return ResourceManager.GetString("DemographicIntake_LastGrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Living Arrangement.
        /// </summary>
        public static string DemographicIntake_LivingArrangement {
            get {
                return ResourceManager.GetString("DemographicIntake_LivingArrangement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marital Status.
        /// </summary>
        public static string DemographicIntake_MaritalStatus {
            get {
                return ResourceManager.GetString("DemographicIntake_MaritalStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # of people in household.
        /// </summary>
        public static string DemographicIntake_NumberOfPeopleInHousehold {
            get {
                return ResourceManager.GetString("DemographicIntake_NumberOfPeopleInHousehold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # of people on your tax return.
        /// </summary>
        public static string DemographicIntake_NumberOfPeopleOnYourTaxReturn {
            get {
                return ResourceManager.GetString("DemographicIntake_NumberOfPeopleOnYourTaxReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occupation.
        /// </summary>
        public static string DemographicIntake_Occupation {
            get {
                return ResourceManager.GetString("DemographicIntake_Occupation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to School Name.
        /// </summary>
        public static string DemographicIntake_SchoolName {
            get {
                return ResourceManager.GetString("DemographicIntake_SchoolName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emergency Contact Name.
        /// </summary>
        public static string EmergencyName {
            get {
                return ResourceManager.GetString("EmergencyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emergency PhoneNumber.
        /// </summary>
        public static string EmergencyPhone {
            get {
                return ResourceManager.GetString("EmergencyPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expire Date.
        /// </summary>
        public static string ExpireDate {
            get {
                return ResourceManager.GetString("ExpireDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id Number.
        /// </summary>
        public static string IdNumber {
            get {
                return ResourceManager.GetString("IdNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string IntroMethodDescription {
            get {
                return ResourceManager.GetString("IntroMethodDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduction Methods.
        /// </summary>
        public static string IntroMethodId {
            get {
                return ResourceManager.GetString("IntroMethodId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notice Accepted.
        /// </summary>
        public static string IsNoticeAccepted {
            get {
                return ResourceManager.GetString("IsNoticeAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Volunteer.
        /// </summary>
        public static string IsVolunteer {
            get {
                return ResourceManager.GetString("IsVolunteer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle Name.
        /// </summary>
        public static string MiddleName {
            get {
                return ResourceManager.GetString("MiddleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Confirmation.
        /// </summary>
        public static string PasswordConfirmation {
            get {
                return ResourceManager.GetString("PasswordConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile Image.
        /// </summary>
        public static string ProfileImage {
            get {
                return ResourceManager.GetString("ProfileImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Race Nationality.
        /// </summary>
        public static string RaceNationality {
            get {
                return ResourceManager.GetString("RaceNationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Region_Type {
            get {
                return ResourceManager.GetString("Region.Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Name.
        /// </summary>
        public static string RoleName {
            get {
                return ResourceManager.GetString("RoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenant Name.
        /// </summary>
        public static string TenantName {
            get {
                return ResourceManager.GetString("TenantName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string UserAddress_Address {
            get {
                return ResourceManager.GetString("UserAddress_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string UserAddress_AddressType {
            get {
                return ResourceManager.GetString("UserAddress_AddressType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string UserAddress_Description {
            get {
                return ResourceManager.GetString("UserAddress_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsDefault.
        /// </summary>
        public static string UserAddress_IsDefault {
            get {
                return ResourceManager.GetString("UserAddress_IsDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region.
        /// </summary>
        public static string UserAddress_Region {
            get {
                return ResourceManager.GetString("UserAddress_Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserId.
        /// </summary>
        public static string UserAddress_UserId {
            get {
                return ResourceManager.GetString("UserAddress_UserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip code.
        /// </summary>
        public static string UserAddress_ZipCode {
            get {
                return ResourceManager.GetString("UserAddress_ZipCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content.
        /// </summary>
        public static string UserAttachment_Content {
            get {
                return ResourceManager.GetString("UserAttachment.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string UserAttachment_Description {
            get {
                return ResourceManager.GetString("UserAttachment.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsDefault.
        /// </summary>
        public static string UserAttachment_IsDefault {
            get {
                return ResourceManager.GetString("UserAttachment.IsDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string UserAttachment_Type {
            get {
                return ResourceManager.GetString("UserAttachment.Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL.
        /// </summary>
        public static string UserAttachment_URL {
            get {
                return ResourceManager.GetString("UserAttachment.URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserId.
        /// </summary>
        public static string UserAttachment_UserId {
            get {
                return ResourceManager.GetString("UserAttachment.UserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string UserPhoneNumber_Description {
            get {
                return ResourceManager.GetString("UserPhoneNumber.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsDefault.
        /// </summary>
        public static string UserPhoneNumber_IsDefault {
            get {
                return ResourceManager.GetString("UserPhoneNumber.IsDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number.
        /// </summary>
        public static string UserPhoneNumber_PhoneNumber {
            get {
                return ResourceManager.GetString("UserPhoneNumber.PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string UserPhoneNumber_Type {
            get {
                return ResourceManager.GetString("UserPhoneNumber.Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserId.
        /// </summary>
        public static string UserPhoneNumber_UserId {
            get {
                return ResourceManager.GetString("UserPhoneNumber.UserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        public static string UserProfile_Height {
            get {
                return ResourceManager.GetString("UserProfile_Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight.
        /// </summary>
        public static string UserProfile_Weight {
            get {
                return ResourceManager.GetString("UserProfile_Weight", resourceCulture);
            }
        }
    }
}
