using WRMC.Infrastructure.Domain.Entities;
using WRMC.Infrastructure.Domain.Enums;

namespace WRMC.Infrastructure.DataAccess.Context
{
    static partial class Seed
    {

        internal static List<Region> Countries = new List<Region> {
            new Region { Id=1 , Name ="Afghanistan", OfficialName = "the Islamic Republic of Afghanistan", ParentId = null ,Iso2="af", Iso3="AFG", RegionType=RegionTypeEnum.Country},
            new Region { Id=2 , Name ="Albania", OfficialName = "the Republic of Albania", ParentId = null ,Iso2="al", Iso3="ALB", RegionType=RegionTypeEnum.Country},
            new Region { Id=3 , Name ="Algeria", OfficialName = "the People's Democratic Republic of Algeria", ParentId = null ,Iso2="dz", Iso3="DZA", RegionType=RegionTypeEnum.Country},
            new Region { Id=4 , Name ="Andorra", OfficialName = "the Principality of Andorra", ParentId = null ,Iso2="ad", Iso3="AND", RegionType=RegionTypeEnum.Country},
            new Region { Id=5 , Name ="Angola", OfficialName = "the Republic of Angola", ParentId = null ,Iso2="ao", Iso3="AGO", RegionType=RegionTypeEnum.Country},
            new Region { Id=6 , Name ="Antigua and Barbuda", OfficialName = "Antigua and Barbuda", ParentId = null ,Iso2="ag", Iso3="ATG", RegionType=RegionTypeEnum.Country},
            new Region { Id=7 , Name ="Argentina", OfficialName = "the Argentine Republic", ParentId = null ,Iso2="ar", Iso3="ARG", RegionType=RegionTypeEnum.Country},
            new Region { Id=8 , Name ="Armenia", OfficialName = "the Republic of Armenia", ParentId = null ,Iso2="am", Iso3="ARM", RegionType=RegionTypeEnum.Country},
            new Region { Id=9 , Name ="Australia", OfficialName = "Australia", ParentId = null ,Iso2="au", Iso3="AUS", RegionType=RegionTypeEnum.Country},
            new Region { Id=10 , Name ="Austria", OfficialName = "the Republic of Austria", ParentId = null ,Iso2="at", Iso3="AUT", RegionType=RegionTypeEnum.Country},
            new Region { Id=11 , Name ="Azerbaijan", OfficialName = "the Republic of Azerbaijan", ParentId = null ,Iso2="az", Iso3="AZE", RegionType=RegionTypeEnum.Country},
            new Region { Id=12 , Name ="Bahamas", OfficialName = "the Commonwealth of the Bahamas", ParentId = null ,Iso2="bs", Iso3="BHS", RegionType=RegionTypeEnum.Country},
            new Region { Id=13 , Name ="Bahrain", OfficialName = "the Kingdom of Bahrain", ParentId = null ,Iso2="bh", Iso3="BHR", RegionType=RegionTypeEnum.Country},
            new Region { Id=14 , Name ="Bangladesh", OfficialName = "the People's Republic of Bangladesh", ParentId = null ,Iso2="bd", Iso3="BGD", RegionType=RegionTypeEnum.Country},
            new Region { Id=15 , Name ="Barbados", OfficialName = "Barbados", ParentId = null ,Iso2="bb", Iso3="BRB", RegionType=RegionTypeEnum.Country},
            new Region { Id=16 , Name ="Belarus", OfficialName = "the Republic of Belarus", ParentId = null ,Iso2="by", Iso3="BLR", RegionType=RegionTypeEnum.Country},
            new Region { Id=17 , Name ="Belgium", OfficialName = "the Kingdom of Belgium", ParentId = null ,Iso2="be", Iso3="BEL", RegionType=RegionTypeEnum.Country},
            new Region { Id=18 , Name ="Belize", OfficialName = "Belize", ParentId = null ,Iso2="bz", Iso3="BLZ", RegionType=RegionTypeEnum.Country},
            new Region { Id=19 , Name ="Benin", OfficialName = "the Republic of Benin", ParentId = null ,Iso2="bj", Iso3="BEN", RegionType=RegionTypeEnum.Country},
            new Region { Id=20 , Name ="Bhutan", OfficialName = "the Kingdom of Bhutan", ParentId = null ,Iso2="bt", Iso3="BTN", RegionType=RegionTypeEnum.Country},
            new Region { Id=21 , Name ="Bolivia (Plurinational State of)", OfficialName = "the Plurinational State of Bolivia", ParentId = null , Iso2="bo",Iso3="BOL", RegionType=RegionTypeEnum.Country},
            new Region { Id=22 , Name ="Bosnia and Herzegovina", OfficialName = "Bosnia and Herzegovina", ParentId = null ,Iso2="ba", Iso3="BIH", RegionType=RegionTypeEnum.Country},
            new Region { Id=23 , Name ="Botswana", OfficialName = "the Republic of Botswana", ParentId = null , Iso2="bw",Iso3="BWA", RegionType=RegionTypeEnum.Country},
            new Region { Id=24 , Name ="Brazil", OfficialName = "the Federative Republic of Brazil", ParentId = null , Iso2="br",Iso3="BRA", RegionType=RegionTypeEnum.Country},
            new Region { Id=25 , Name ="Brunei Darussalam", OfficialName = "Brunei Darussalam", ParentId = null , Iso2="bn",Iso3="BRN", RegionType=RegionTypeEnum.Country},
            new Region { Id=26 , Name ="Bulgaria", OfficialName = "the Republic of Bulgaria", ParentId = null ,Iso2="bg", Iso3="BGR", RegionType=RegionTypeEnum.Country},
            new Region { Id=27 , Name ="Burkina Faso", OfficialName = "Burkina Faso", ParentId = null , Iso2="bf",Iso3="BFA", RegionType=RegionTypeEnum.Country},
            new Region { Id=28 , Name ="Burundi", OfficialName = "the Republic of Burundi", ParentId = null ,Iso2="bi", Iso3="BDI", RegionType=RegionTypeEnum.Country},
            new Region { Id=29 , Name ="Cabo Verde", OfficialName = "Republic of Cabo Verde", ParentId = null , Iso2="cv",Iso3="CPV", RegionType=RegionTypeEnum.Country},
            new Region { Id=30 , Name ="Cambodia", OfficialName = "the Kingdom of Cambodia", ParentId = null , Iso2="kh",Iso3="KHM", RegionType=RegionTypeEnum.Country},
            new Region { Id=31 , Name ="Cameroon", OfficialName = "the Republic of Cameroon", ParentId = null , Iso2="cm",Iso3="CMR", RegionType=RegionTypeEnum.Country},
            new Region { Id=32 , Name ="Canada", OfficialName = "Canada", ParentId = null , Iso2="ca",Iso3="CAN", RegionType=RegionTypeEnum.Country},
            new Region { Id=33 , Name ="Central African Republic", OfficialName = "the Central African Republic", ParentId = null ,Iso2="cf", Iso3="CAF", RegionType=RegionTypeEnum.Country},
            new Region { Id=34 , Name ="Chad", OfficialName = "the Republic of Chad", ParentId = null , Iso2="td",Iso3="TCD", RegionType=RegionTypeEnum.Country},
            new Region { Id=35 , Name ="Chile", OfficialName = "the Republic of Chile", ParentId = null ,Iso2="cl", Iso3="CHL", RegionType=RegionTypeEnum.Country},
            new Region { Id=36 , Name ="China", OfficialName = "the People's Republic of China", ParentId = null , Iso2="cn",Iso3="CHN", RegionType=RegionTypeEnum.Country},
            new Region { Id=37 , Name ="Colombia", OfficialName = "the Republic of Colombia", ParentId = null , Iso2="co",Iso3="COL", RegionType=RegionTypeEnum.Country},
            new Region { Id=38 , Name ="Comoros", OfficialName = "the Union of the Comoros", ParentId = null ,Iso2="km", Iso3="COM", RegionType=RegionTypeEnum.Country},
            new Region { Id=39 , Name ="Congo", OfficialName = "the Republic of the Congo", ParentId = null ,Iso2="cg", Iso3="COG", RegionType=RegionTypeEnum.Country},
            new Region { Id=40 , Name ="Cook Islands", OfficialName = "the Cook Islands", ParentId = null , Iso2="ck",Iso3="COK", RegionType=RegionTypeEnum.Country},
            new Region { Id=41 , Name ="Costa Rica", OfficialName = "the Republic of Costa Rica", ParentId = null ,Iso2="cr", Iso3="CRI", RegionType=RegionTypeEnum.Country},
            new Region { Id=42 , Name ="Croatia", OfficialName = "the Republic of Croatia", ParentId = null , Iso2="hr",Iso3="HRV", RegionType=RegionTypeEnum.Country},
            new Region { Id=43 , Name ="Cuba", OfficialName = "the Republic of Cuba", ParentId = null, Iso2="cu", Iso3="CUB", RegionType=RegionTypeEnum.Country},
            new Region { Id=44 , Name ="Cyprus", OfficialName = "the Republic of Cyprus", ParentId = null ,Iso2="cy", Iso3="CYP", RegionType=RegionTypeEnum.Country},
            new Region { Id=45 , Name ="Czechia", OfficialName = "the Czech Republic", ParentId = null ,Iso2="cz", Iso3="CZE", RegionType=RegionTypeEnum.Country},
            new Region { Id=46 , Name ="CÃ´te d'Ivoire", OfficialName = "the Republic of CÃ´te d'Ivoire", ParentId = null , Iso2="ci",Iso3="CIV", RegionType=RegionTypeEnum.Country},
            new Region { Id=47 , Name ="Democratic People's Republic of Korea", OfficialName = "the Democratic People's Republic of Korea", ParentId = null ,Iso2="kp", Iso3="PRK", RegionType=RegionTypeEnum.Country},
            new Region { Id=48 , Name ="Democratic Republic of the Congo", OfficialName = "the Democratic Republic of the Congo", ParentId = null ,Iso2="cd", Iso3="COD", RegionType=RegionTypeEnum.Country},
            new Region { Id=49 , Name ="Denmark", OfficialName = "the Kingdom of Denmark", ParentId = null , Iso2="dk",Iso3="DNK", RegionType=RegionTypeEnum.Country},
            new Region { Id=50 , Name ="Djibouti", OfficialName = "the Republic of Djibouti", ParentId = null , Iso2="dj",Iso3="DJI", RegionType=RegionTypeEnum.Country},
            new Region { Id=51 , Name ="Dominica", OfficialName = "the Commonwealth of Dominica", ParentId = null , Iso2="dm",Iso3="DMA", RegionType=RegionTypeEnum.Country},
            new Region { Id=52 , Name ="Dominican Republic", OfficialName = "the Dominican Republic", ParentId = null ,Iso2="do", Iso3="DOM", RegionType=RegionTypeEnum.Country},
            new Region { Id=53 , Name ="Ecuador", OfficialName = "the Republic of Ecuador", ParentId = null ,Iso2="ec", Iso3="ECU", RegionType=RegionTypeEnum.Country},
            new Region { Id=54 , Name ="Egypt", OfficialName = "the Arab Republic of Egypt", ParentId = null ,Iso2="eg", Iso3="EGY", RegionType=RegionTypeEnum.Country},
            new Region { Id=55 , Name ="El Salvador", OfficialName = "the Republic of El Salvador", ParentId = null ,Iso2="sv", Iso3="SLV", RegionType=RegionTypeEnum.Country},
            new Region { Id=56 , Name ="Equatorial Guinea", OfficialName = "the Republic of Equatorial Guinea",Iso2="gq", ParentId = null , Iso3="GNQ", RegionType=RegionTypeEnum.Country},
            new Region { Id=57 , Name ="Eritrea", OfficialName = "the State of Eritrea", ParentId = null , Iso2="er",Iso3="ERI", RegionType=RegionTypeEnum.Country},
            new Region { Id=58 , Name ="Estonia", OfficialName = "the Republic of Estonia", ParentId = null ,Iso2="ce", Iso3="EST", RegionType=RegionTypeEnum.Country},
            new Region { Id=59 , Name ="Eswatini", OfficialName = "the Kingdom of Eswatini", ParentId = null ,Iso2="sz", Iso3="SWZ", RegionType=RegionTypeEnum.Country},
            new Region { Id=60 , Name ="Ethiopia", OfficialName = "the Federal Democratic Republic of Ethiopia",Iso2="et", ParentId = null , Iso3="ETH", RegionType=RegionTypeEnum.Country},
            new Region { Id=61 , Name ="Faroe Islands", OfficialName = "Faroe Islands", ParentId = null ,Iso2="fo", Iso3="FRO", RegionType=RegionTypeEnum.Country},
            new Region { Id=62 , Name ="Fiji", OfficialName = "the Republic of Fiji", ParentId = null ,Iso2="fj", Iso3="FJI", RegionType=RegionTypeEnum.Country},
            new Region { Id=63 , Name ="Finland", OfficialName = "the Republic of Finland", ParentId = null ,Iso2="fi", Iso3="FIN", RegionType=RegionTypeEnum.Country},
            new Region { Id=64 , Name ="France", OfficialName = "the French Republic", ParentId = null , Iso2="fr",Iso3="FRA", RegionType=RegionTypeEnum.Country},
            new Region { Id=65 , Name ="Gabon", OfficialName = "the Gabonese Republic", ParentId = null ,Iso2="ga", Iso3="GAB", RegionType=RegionTypeEnum.Country},
            new Region { Id=66 , Name ="Gambia", OfficialName = "the Republic of the Gambia", ParentId = null ,Iso2="gm", Iso3="GMB", RegionType=RegionTypeEnum.Country},
            new Region { Id=67 , Name ="Georgia", OfficialName = "Georgia", ParentId = null ,Iso2="ge", Iso3="GEO", RegionType=RegionTypeEnum.Country},
            new Region { Id=68 , Name ="Germany", OfficialName = "the Federal Republic of Germany", Iso2="de",ParentId = null , Iso3="DEU", RegionType=RegionTypeEnum.Country},
            new Region { Id=69 , Name ="Ghana", OfficialName = "the Republic of Ghana", ParentId = null ,Iso2="gh", Iso3="GHA", RegionType=RegionTypeEnum.Country},
            new Region { Id=70 , Name ="Greece", OfficialName = "the Hellenic Republic", ParentId = null ,Iso2="gr", Iso3="GRC", RegionType=RegionTypeEnum.Country},
            new Region { Id=71 , Name ="Grenada", OfficialName = "Grenada", ParentId = null ,Iso2="gd", Iso3="GRD", RegionType=RegionTypeEnum.Country},
            new Region { Id=72 , Name ="Guatemala", OfficialName = "the Republic of Guatemala", ParentId = null ,Iso2="gt", Iso3="GTM", RegionType=RegionTypeEnum.Country},
            new Region { Id=73 , Name ="Guinea", OfficialName = "the Republic of Guinea", ParentId = null ,Iso2="gn", Iso3="GIN", RegionType=RegionTypeEnum.Country},
            new Region { Id=74 , Name ="Guinea-Bissau", OfficialName = "the Republic of Guinea-Bissau", ParentId = null ,Iso2="gw", Iso3="GNB", RegionType=RegionTypeEnum.Country},
            new Region { Id=75 , Name ="Guyana", OfficialName = "the Co-operative Republic of Guyana", ParentId = null ,Iso2="gy", Iso3="GUY", RegionType=RegionTypeEnum.Country},
            new Region { Id=76 , Name ="Haiti", OfficialName = "the Republic of Haiti", ParentId = null ,Iso2="ht", Iso3="HTI", RegionType=RegionTypeEnum.Country},
            new Region { Id=77 , Name ="Honduras", OfficialName = "the Republic of Honduras", ParentId = null ,Iso2="hn", Iso3="HND", RegionType=RegionTypeEnum.Country},
            new Region { Id=78 , Name ="Hungary", OfficialName = "Hungary", ParentId = null , Iso2="hu",Iso3="HUN", RegionType=RegionTypeEnum.Country},
            new Region { Id=79 , Name ="Iceland", OfficialName = "the Republic of Iceland", ParentId = null ,Iso2="is", Iso3="ISL", RegionType=RegionTypeEnum.Country},
            new Region { Id=80 , Name ="India", OfficialName = "the Republic of India", ParentId = null ,Iso2="in", Iso3="IND", RegionType=RegionTypeEnum.Country},
            new Region { Id=81 , Name ="Indonesia", OfficialName = "the Republic of Indonesia", ParentId = null , Iso2="id",Iso3="IDN", RegionType=RegionTypeEnum.Country},
            new Region { Id=82 , Name ="Iran (Islamic Republic of)", OfficialName = "the Islamic Republic of Iran", ParentId = null ,Iso2="ir", Iso3="IRN", RegionType=RegionTypeEnum.Country},
            new Region { Id=83 , Name ="Iraq", OfficialName = "the Republic of Iraq", ParentId = null ,Iso2="iq", Iso3="IRQ", RegionType=RegionTypeEnum.Country},
            new Region { Id=84 , Name ="Ireland", OfficialName = "Ireland", ParentId = null , Iso2="ie",Iso3="IRL", RegionType=RegionTypeEnum.Country},
            new Region { Id=85 , Name ="Israel", OfficialName = "the State of Israel", ParentId = null , Iso2="il",Iso3="ISR", RegionType=RegionTypeEnum.Country},
            new Region { Id=86 , Name ="Italy", OfficialName = "the Republic of Italy", ParentId = null ,Iso2="it", Iso3="ITA", RegionType=RegionTypeEnum.Country},
            new Region { Id=87 , Name ="Jamaica", OfficialName = "Jamaica", ParentId = null ,Iso2="jm", Iso3="JAM", RegionType=RegionTypeEnum.Country},
            new Region { Id=88 , Name ="Japan", OfficialName = "Japan", ParentId = null , Iso2="jp",Iso3="JPN", RegionType=RegionTypeEnum.Country},
            new Region { Id=89 , Name ="Jordan", OfficialName = "the Hashemite Kingdom of Jordan", ParentId = null ,Iso2="jo", Iso3="JOR", RegionType=RegionTypeEnum.Country},
            new Region { Id=90 , Name ="Kazakhstan", OfficialName = "the Republic of Kazakhstan", ParentId = null ,Iso2="kz", Iso3="KAZ", RegionType=RegionTypeEnum.Country},
            new Region { Id=91 , Name ="Kenya", OfficialName = "the Republic of Kenya", ParentId = null ,Iso2="kn", Iso3="KEN", RegionType=RegionTypeEnum.Country},
            new Region { Id=92 , Name ="Kiribati", OfficialName = "the Republic of Kiribati", ParentId = null ,Iso2="ki", Iso3="KIR", RegionType=RegionTypeEnum.Country},
            new Region { Id=93 , Name ="Kuwait", OfficialName = "the State of Kuwait", ParentId = null , Iso2="kw",Iso3="KWT", RegionType=RegionTypeEnum.Country},
            new Region { Id=94 , Name ="Kyrgyzstan", OfficialName = "the Kyrgyz Republic", ParentId = null ,Iso2="kg", Iso3="KGZ", RegionType=RegionTypeEnum.Country},
            new Region { Id=95 , Name ="Lao People's Democratic Republic", OfficialName = "the Lao People's Democratic Republic", ParentId = null , Iso2="la",Iso3="LAO", RegionType=RegionTypeEnum.Country},
            new Region { Id=96 , Name ="Latvia", OfficialName = "the Republic of Latvia", ParentId = null ,Iso2="lv",Iso3="LVA", RegionType=RegionTypeEnum.Country},
            new Region { Id=97 , Name ="Lebanon", OfficialName = "the Lebanese Republic", ParentId = null , Iso2="lb",Iso3="LBN", RegionType=RegionTypeEnum.Country},
            new Region { Id=98 , Name ="Lesotho", OfficialName = "the Kingdom of Lesotho", ParentId = null ,Iso2="ls", Iso3="LSO", RegionType=RegionTypeEnum.Country},
            new Region { Id=99 , Name ="Liberia", OfficialName = "the Republic of Liberia", ParentId = null , Iso2="lr",Iso3="LBR", RegionType=RegionTypeEnum.Country},
            new Region { Id=100 , Name ="Libya", OfficialName = "State of Libya", ParentId = null , Iso2="ly",Iso3="LBY", RegionType=RegionTypeEnum.Country},
            new Region { Id=101 , Name ="Lithuania", OfficialName = "the Republic of Lithuania", ParentId = null ,Iso2="lt", Iso3="LTU", RegionType=RegionTypeEnum.Country},
            new Region { Id=102 , Name ="Luxembourg", OfficialName = "the Grand Duchy of Luxembourg", ParentId = null ,Iso2="lu", Iso3="LUX", RegionType=RegionTypeEnum.Country},
            new Region { Id=103 , Name ="Madagascar", OfficialName = "the Republic of Madagascar", ParentId = null ,Iso2="mg", Iso3="MDG", RegionType=RegionTypeEnum.Country},
            new Region { Id=104 , Name ="Malawi", OfficialName = "the Republic of Malawi", ParentId = null ,Iso2="mw", Iso3="MWI", RegionType=RegionTypeEnum.Country},
            new Region { Id=105 , Name ="Malaysia", OfficialName = "Malaysia", ParentId = null ,Iso2="my", Iso3="MYS", RegionType=RegionTypeEnum.Country},
            new Region { Id=106 , Name ="Maldives", OfficialName = "the Republic of Maldives", ParentId = null ,Iso2="mv", Iso3="MDV", RegionType=RegionTypeEnum.Country},
            new Region { Id=107 , Name ="Mali", OfficialName = "the Republic of Mali", ParentId = null , Iso2="ml",Iso3="MLI", RegionType=RegionTypeEnum.Country},
            new Region { Id=108 , Name ="Malta", OfficialName = "the Republic of Malta", ParentId = null , Iso2="mt",Iso3="MLT", RegionType=RegionTypeEnum.Country},
            new Region { Id=109 , Name ="Marshall Islands", OfficialName = "the Republic of the Marshall Islands", ParentId = null ,Iso2="mh", Iso3="MHL", RegionType=RegionTypeEnum.Country},
            new Region { Id=110 , Name ="Mauritania", OfficialName = "the Islamic Republic of Mauritania", ParentId = null ,Iso2="mr", Iso3="MRT", RegionType=RegionTypeEnum.Country},
            new Region { Id=111 , Name ="Mauritius", OfficialName = "the Republic of Mauritius", ParentId = null ,Iso2="mu", Iso3="MUS", RegionType=RegionTypeEnum.Country},
            new Region { Id=112 , Name ="Mexico", OfficialName = "the United Mexican States", ParentId = null , Iso2="mx",Iso3="MEX", RegionType=RegionTypeEnum.Country},
            new Region { Id=113 , Name ="Micronesia (Federated States of)", OfficialName = "the Federated States of Micronesia", ParentId = null ,Iso2="fm", Iso3="FSM", RegionType=RegionTypeEnum.Country},
            new Region { Id=114 , Name ="Monaco", OfficialName = "the Principality of Monaco", ParentId = null ,Iso2="mc",Iso3="MCO", RegionType=RegionTypeEnum.Country},
            new Region { Id=115 , Name ="Mongolia", OfficialName = "Mongolia", ParentId = null ,Iso2="mn", Iso3="MNG", RegionType=RegionTypeEnum.Country},
            new Region { Id=116 , Name ="Montenegro", OfficialName = "Montenegro", ParentId = null ,Iso2="me", Iso3="MNE", RegionType=RegionTypeEnum.Country},
            new Region { Id=117 , Name ="Morocco", OfficialName = "the Kingdom of Morocco", ParentId = null ,Iso2="ma", Iso3="MAR", RegionType=RegionTypeEnum.Country},
            new Region { Id=118 , Name ="Mozambique", OfficialName = "the Republic of Mozambique", ParentId = null ,Iso2="mz", Iso3="MOZ", RegionType=RegionTypeEnum.Country},
            new Region { Id=119 , Name ="Myanmar", OfficialName = "the Republic of the Union of Myanmar", ParentId = null ,Iso2="mm", Iso3="MMR", RegionType=RegionTypeEnum.Country},
            new Region { Id=120 , Name ="Namibia", OfficialName = "the Republic of Namibia", ParentId = null ,Iso2="na", Iso3="NAM", RegionType=RegionTypeEnum.Country},
            new Region { Id=121 , Name ="Nauru", OfficialName = "the Republic of Nauru", ParentId = null , Iso2="nr",Iso3="NRU", RegionType=RegionTypeEnum.Country},
            new Region { Id=122 , Name ="Nepal", OfficialName = "the Federal Democratic Republic of Nepal", ParentId = null ,Iso2="np", Iso3="NPL", RegionType=RegionTypeEnum.Country},
            new Region { Id=123 , Name ="Netherlands", OfficialName = "the Kingdom of the Netherlands", ParentId = null ,Iso2="nl", Iso3="NLD", RegionType=RegionTypeEnum.Country},
            new Region { Id=124 , Name ="New Zealand", OfficialName = "New Zealand", ParentId = null ,Iso2="nz", Iso3="NZL", RegionType=RegionTypeEnum.Country},
            new Region { Id=125 , Name ="Nicaragua", OfficialName = "the Republic of Nicaragua", ParentId = null ,Iso2="ni", Iso3="NIC", RegionType=RegionTypeEnum.Country},
            new Region { Id=126 , Name ="Niger", OfficialName = "the Republic of the Niger", ParentId = null , Iso2="ne",Iso3="NER", RegionType=RegionTypeEnum.Country},
            new Region { Id=127 , Name ="Nigeria", OfficialName = "the Federal Republic of Nigeria", ParentId = null , Iso2="ng",Iso3="NGA", RegionType=RegionTypeEnum.Country},
            new Region { Id=128 , Name ="Niue", OfficialName = "Niue", ParentId = null ,Iso2="nu",Iso3="NIU", RegionType=RegionTypeEnum.Country},
            new Region { Id=129 , Name ="North Macedonia", OfficialName = "the Republic of North Macedonia", ParentId = null ,Iso2="mk", Iso3="MKD", RegionType=RegionTypeEnum.Country},
            new Region { Id=130 , Name ="Norway", OfficialName = "the Kingdom of Norway", ParentId = null ,Iso2="no", Iso3="NOR", RegionType=RegionTypeEnum.Country},
            new Region { Id=131 , Name ="Oman", OfficialName = "the Sultanate of Oman", ParentId = null ,Iso2="om", Iso3="OMN", RegionType=RegionTypeEnum.Country},
            new Region { Id=132 , Name ="Pakistan", OfficialName = "the Islamic Republic of Pakistan", ParentId = null ,Iso2="pk", Iso3="PAK", RegionType=RegionTypeEnum.Country},
            new Region { Id=133 , Name ="Palau", OfficialName = "the Republic of Palau", ParentId = null ,Iso2="pw", Iso3="PLW", RegionType=RegionTypeEnum.Country},
            new Region { Id=134 , Name ="Panama", OfficialName = "the Republic of Panama", ParentId = null ,Iso2="pa", Iso3="PAN", RegionType=RegionTypeEnum.Country},
            new Region { Id=135 , Name ="Papua New Guinea", OfficialName = "Independent State of Papua New Guinea", ParentId = null ,Iso2="pg", Iso3="PNG", RegionType=RegionTypeEnum.Country},
            new Region { Id=136 , Name ="Paraguay", OfficialName = "the Republic of Paraguay", ParentId = null , Iso2="py",Iso3="PRY", RegionType=RegionTypeEnum.Country},
            new Region { Id=137 , Name ="Peru", OfficialName = "the Republic of Peru", ParentId = null ,Iso2="pe", Iso3="PER", RegionType=RegionTypeEnum.Country},
            new Region { Id=138 , Name ="Philippines", OfficialName = "the Republic of the Philippines", ParentId = null ,Iso2="ph",Iso3="PHL", RegionType=RegionTypeEnum.Country},
            new Region { Id=139 , Name ="Poland", OfficialName = "the Republic of Poland", ParentId = null ,Iso2="pl", Iso3="POL", RegionType=RegionTypeEnum.Country},
            new Region { Id=140 , Name ="Portugal", OfficialName = "the Portuguese Republic", ParentId = null ,Iso2="pt", Iso3="PRT", RegionType=RegionTypeEnum.Country},
            new Region { Id=141 , Name ="Qatar", OfficialName = "the State of Qatar", ParentId = null ,Iso2="qa", Iso3="QAT", RegionType=RegionTypeEnum.Country},
            new Region { Id=142 , Name ="Republic of Korea", OfficialName = "the Republic of Korea", ParentId = null , Iso2="kr",Iso3="KOR", RegionType=RegionTypeEnum.Country},
            new Region { Id=143 , Name ="Republic of Moldova", OfficialName = "the Republic of Moldova", ParentId = null ,Iso2="md", Iso3="MDA", RegionType=RegionTypeEnum.Country},
            new Region { Id=144 , Name ="Romania", OfficialName = "Romania", ParentId = null ,Iso2="ro", Iso3="ROU", RegionType=RegionTypeEnum.Country},
            new Region { Id=145 , Name ="Russian Federation", OfficialName = "the Russian Federation", ParentId = null ,Iso2="ru", Iso3="RUS", RegionType=RegionTypeEnum.Country},
            new Region { Id=146 , Name ="Rwanda", OfficialName = "the Republic of Rwanda", ParentId = null ,Iso2="rw", Iso3="RWA", RegionType=RegionTypeEnum.Country},
            new Region { Id=147 , Name ="Saint Kitts and Nevis", OfficialName = "Saint Kitts and Nevis", ParentId = null ,Iso2="kn", Iso3="KNA", RegionType=RegionTypeEnum.Country},
            new Region { Id=148 , Name ="Saint Lucia", OfficialName = "Saint Lucia", ParentId = null ,Iso2="lc", Iso3="LCA", RegionType=RegionTypeEnum.Country},
            new Region { Id=149 , Name ="Saint Vincent and the Grenadines", OfficialName = "Saint Vincent and the Grenadines", ParentId = null ,Iso2="vc", Iso3="VCT", RegionType=RegionTypeEnum.Country},
            new Region { Id=150 , Name ="Samoa", OfficialName = "the Independent State of Samoa", ParentId = null ,Iso2="ws", Iso3="WSM", RegionType=RegionTypeEnum.Country},
            new Region { Id=151 , Name ="San Marino", OfficialName = "the Republic of San Marino", ParentId = null ,Iso2="sm", Iso3="SMR", RegionType=RegionTypeEnum.Country},
            new Region { Id=152 , Name ="Sao Tome and Principe", OfficialName = "the Democratic Republic of Sao Tome and Principe", ParentId = null ,Iso2="st", Iso3="STP", RegionType=RegionTypeEnum.Country},
            new Region { Id=153 , Name ="Saudi Arabia", OfficialName = "the Kingdom of Saudi Arabia", ParentId = null ,Iso2="sa", Iso3="SAU", RegionType=RegionTypeEnum.Country},
            new Region { Id=154 , Name ="Senegal", OfficialName = "the Republic of Senegal", ParentId = null , Iso2="sn",Iso3="SEN", RegionType=RegionTypeEnum.Country},
            new Region { Id=155 , Name ="Serbia", OfficialName = "the Republic of Serbia", ParentId = null ,Iso2="rs", Iso3="SRB", RegionType=RegionTypeEnum.Country},
            new Region { Id=156 , Name ="Seychelles", OfficialName = "the Republic of Seychelles", ParentId = null ,Iso2="sc", Iso3="SYC", RegionType=RegionTypeEnum.Country},
            new Region { Id=157 , Name ="Sierra Leone", OfficialName = "the Republic of Sierra Leone", ParentId = null , Iso2="sl",Iso3="SLE", RegionType=RegionTypeEnum.Country},
            new Region { Id=158 , Name ="Singapore", OfficialName = "the Republic of Singapore", ParentId = null ,Iso2="sg", Iso3="SGP", RegionType=RegionTypeEnum.Country},
            new Region { Id=159 , Name ="Slovakia", OfficialName = "the Slovak Republic", ParentId = null ,Iso2="sk", Iso3="SVK", RegionType=RegionTypeEnum.Country},
            new Region { Id=160 , Name ="Slovenia", OfficialName = "the Republic of Slovenia", ParentId = null , Iso2="si",Iso3="SVN", RegionType=RegionTypeEnum.Country},
            new Region { Id=161 , Name ="Solomon Islands", OfficialName = "Solomon Islands", ParentId = null ,Iso2="sb", Iso3="SLB", RegionType=RegionTypeEnum.Country},
            new Region { Id=162 , Name ="Somalia", OfficialName = "the Federal Republic of Somalia", ParentId = null ,Iso2="so", Iso3="SOM", RegionType=RegionTypeEnum.Country},
            new Region { Id=163 , Name ="South Africa", OfficialName = "the Republic of South Africa", ParentId = null ,Iso2="za", Iso3="ZAF", RegionType=RegionTypeEnum.Country},
            new Region { Id=164 , Name ="South Sudan", OfficialName = "the Republic of South Sudan", ParentId = null ,Iso2="ss", Iso3="SSD", RegionType=RegionTypeEnum.Country},
            new Region { Id=165 , Name ="Spain", OfficialName = "the Kingdom of Spain", ParentId = null ,Iso2="es", Iso3="ESP", RegionType=RegionTypeEnum.Country},
            new Region { Id=166 , Name ="Sri Lanka", OfficialName = "the Democratic Socialist Republic of Sri Lanka", ParentId = null ,Iso2="lk", Iso3="LKA", RegionType=RegionTypeEnum.Country},
            new Region { Id=167 , Name ="Sudan", OfficialName = "the Republic of the Sudan", ParentId = null ,Iso2="sd", Iso3="SDN", RegionType=RegionTypeEnum.Country},
            new Region { Id=168 , Name ="Suriname", OfficialName = "the Republic of Suriname", ParentId = null , Iso2="sr",Iso3="SUR", RegionType=RegionTypeEnum.Country},
            new Region { Id=169 , Name ="Sweden", OfficialName = "the Kingdom of Sweden", ParentId = null ,Iso2="se", Iso3="SWE", RegionType=RegionTypeEnum.Country},
            new Region { Id=170 , Name ="Switzerland", OfficialName = "the Swiss Confederation", ParentId = null ,Iso2="ch", Iso3="CHE", RegionType=RegionTypeEnum.Country},
            new Region { Id=171 , Name ="Syrian Arab Republic", OfficialName = "the Syrian Arab Republic", ParentId = null ,Iso2="sy", Iso3="SYR", RegionType=RegionTypeEnum.Country},
            new Region { Id=172 , Name ="Tajikistan", OfficialName = "the Republic of Tajikistan", ParentId = null ,Iso2="tj", Iso3="TJK", RegionType=RegionTypeEnum.Country},
            new Region { Id=173 , Name ="Thailand", OfficialName = "the Kingdom of Thailand", ParentId = null , Iso2="th",Iso3="THA", RegionType=RegionTypeEnum.Country},
            new Region { Id=174 , Name ="Timor-Leste", OfficialName = "the Democratic Republic of Timor-Leste", ParentId = null , Iso2="tl",Iso3="TLS", RegionType=RegionTypeEnum.Country},
            new Region { Id=175 , Name ="Togo", OfficialName = "the Togolese Republic", ParentId = null ,Iso2="tg", Iso3="TGO", RegionType=RegionTypeEnum.Country},
            new Region { Id=176 , Name ="Tokelau", OfficialName = "Tokelau", ParentId = null ,Iso2="tk", Iso3="TKL", RegionType=RegionTypeEnum.Country},
            new Region { Id=177 , Name ="Tonga", OfficialName = "the Kingdom of Tonga", ParentId = null ,Iso2="to", Iso3="TON", RegionType=RegionTypeEnum.Country},
            new Region { Id=178 , Name ="Trinidad and Tobago", OfficialName = "the Republic of Trinidad and Tobago", ParentId = null ,Iso2="tt", Iso3="TTO", RegionType=RegionTypeEnum.Country},
            new Region { Id=179 , Name ="Tunisia", OfficialName = "the Republic of Tunisia", ParentId = null , Iso2="tn",Iso3="TUN", RegionType=RegionTypeEnum.Country},
            new Region { Id=180 , Name ="Turkey", OfficialName = "the Republic of Turkey", ParentId = null ,Iso2="tr", Iso3="TUR", RegionType=RegionTypeEnum.Country},
            new Region { Id=181 , Name ="Turkmenistan", OfficialName = "Turkmenistan", ParentId = null , Iso2="tm",Iso3="TKM", RegionType=RegionTypeEnum.Country},
            new Region { Id=182 , Name ="Tuvalu", OfficialName = "Tuvalu", ParentId = null ,Iso2="tv", Iso3="TUV", RegionType=RegionTypeEnum.Country},
            new Region { Id=183 , Name ="Uganda", OfficialName = "the Republic of Uganda", ParentId = null ,Iso2="ug", Iso3="UGA", RegionType=RegionTypeEnum.Country},
            new Region { Id=184 , Name ="Ukraine", OfficialName = "Ukraine", ParentId = null , Iso2="ua",Iso3="UKR", RegionType=RegionTypeEnum.Country},
            new Region { Id=185 , Name ="United Arab Emirates", OfficialName = "the United Arab Emirates", ParentId = null ,Iso2="ae", Iso3="ARE", RegionType=RegionTypeEnum.Country},
            new Region { Id=186 , Name ="United Kingdom of Great Britain and Northern Ireland", OfficialName = "the United Kingdom of Great Britain and Northern Ireland", ParentId = null ,Iso2="gb", Iso3="GBR", RegionType=RegionTypeEnum.Country},
            new Region { Id=187 , Name ="United Republic of Tanzania", OfficialName = "the United Republic of Tanzania", ParentId = null , Iso2="tz",Iso3="TZA", RegionType=RegionTypeEnum.Country},
            new Region { Id=188 , Name ="United States of America", OfficialName = "the United States of America", ParentId = null ,Iso2="us", Iso3="USA", RegionType=RegionTypeEnum.Country},
            new Region { Id=189 , Name ="Uruguay", OfficialName = "the Eastern Republic of Uruguay", ParentId = null ,Iso2="uy", Iso3="URY", RegionType=RegionTypeEnum.Country},
            new Region { Id=190 , Name ="Uzbekistan", OfficialName = "the Republic of Uzbekistan", ParentId = null ,Iso2="uz", Iso3="UZB", RegionType=RegionTypeEnum.Country},
            new Region { Id=191 , Name ="Vanuatu", OfficialName = "the Republic of Vanuatu", ParentId = null ,Iso2="vu", Iso3="VUT", RegionType=RegionTypeEnum.Country},
            new Region { Id=192 , Name ="Venezuela (Bolivarian Republic of)", OfficialName = "the Bolivarian Republic of Venezuela", ParentId = null ,Iso2="ve", Iso3="VEN", RegionType=RegionTypeEnum.Country},
            new Region { Id=193 , Name ="Viet Nam", OfficialName = "the Socialist Republic of Viet Nam", ParentId = null ,Iso2="vn", Iso3="VNM", RegionType=RegionTypeEnum.Country},
            new Region { Id=194 , Name ="Yemen", OfficialName = "the Republic of Yemen", ParentId = null ,Iso2="ye", Iso3="YEM", RegionType=RegionTypeEnum.Country},
            new Region { Id=195 , Name ="Zambia", OfficialName = "the Republic of Zambia", ParentId = null ,Iso2="zm", Iso3="ZMB", RegionType=RegionTypeEnum.Country},
            new Region { Id=196 , Name ="Zimbabwe", OfficialName = "the Republic of Zimbabwe", ParentId = null ,Iso2="zw", Iso3="ZWE", RegionType=RegionTypeEnum.Country},
    };
    }
}