using WRMC.Core.Shared.Constants;
using WRMC.Infrastructure.Domain.Entities;
using WRMC.Infrastructure.Domain.Enums;
namespace WRMC.Infrastructure.DataAccess.Context
{

    static partial class Seed
    {

        internal static List<Section> Sections = new List<Section> {
            new Section {//Parent : Null
                Id=Guid.Parse("c3c1384e-9822-49f1-97c5-0d065426329b"),
                ParentId = null,
                SectionGroup = SectionGroupEnum.Category,
                Name = "PregnancyTest",
                DisplayTitle = "Pregnancy Test",
                Help ="Pregnancy Test and Care Plan",
                URI = "PregnancyTest",
                Command = "-",
                IsRequired = false,
                RequiredPolicy = "-",
                Order = 1,
                Visibility = SectionVisibilityEnum.Public,
                SectionType = SectionTypeEnum.None,
                Gender = GenderEnum.Female,
            },
            new Section {//Parent : PregnancyTest
                Id=Guid.Parse("00000001-6df9-4ecb-86c8-000000000001"),
                ParentId = Guid.Parse("c3c1384e-9822-49f1-97c5-0d065426329b"),
                SectionGroup = SectionGroupEnum.Step,
                Visibility = SectionVisibilityEnum.Public,
                SectionType = SectionTypeEnum.None,
                Name = "Step1",
                DisplayTitle = "Step 1",
                Help ="this is step 1",
                URI = "-",
                Command = "-",
                IsRequired = true,
                RequiredPolicy = "-",
                Order = 1,
                Gender = GenderEnum.Female,
            },
            new Section {//Parent : PregnancyTest
                Id=Guid.Parse("00000002-6df9-4ecb-86c8-000000000002"),
                ParentId = Guid.Parse("c3c1384e-9822-49f1-97c5-0d065426329b"),
                SectionGroup = SectionGroupEnum.Step,
                Visibility = SectionVisibilityEnum.Public,
                SectionType = SectionTypeEnum.None,
                Name = "Step2",
                DisplayTitle = "Step 2",
                Help ="this is step 2",
                URI = "-",
                Command = "-",
                IsRequired = true,
                RequiredPolicy = "-",
                Order = 2,
                Gender = GenderEnum.Female,
            }, new Section {//Parent : PregnancyTest
                Id=Guid.Parse("00000003-6df9-4ecb-86c8-000000000003"),
                ParentId = Guid.Parse("c3c1384e-9822-49f1-97c5-0d065426329b"),
                SectionGroup = SectionGroupEnum.Step,
                Visibility = SectionVisibilityEnum.Public,
                SectionType = SectionTypeEnum.None,
                Name = "Step3",
                DisplayTitle = "Step 3",
                Help ="this is step 3",
                URI = "-",
                Command = "-",
                IsRequired = true,
                RequiredPolicy = "-",
                Order = 3,
                Gender = GenderEnum.Female,
            },
            new Section {//Parent : PregnancyTest
                Id=Guid.Parse("00000004-6df9-4ecb-86c8-000000000004"),
                ParentId = Guid.Parse("c3c1384e-9822-49f1-97c5-0d065426329b"),
                SectionGroup = SectionGroupEnum.Step,
                Visibility = SectionVisibilityEnum.Public,
                SectionType = SectionTypeEnum.None,
                Name = "Step4",
                DisplayTitle = "Step 4",
                Help ="this is step 4",
                URI = "-",
                Command = "-",
                IsRequired = true,
                RequiredPolicy = "-",
                Order = 4,
                Gender = GenderEnum.Female,
            },
            new Section {//Parent : PregnancyTest
                Id=Guid.Parse("00000005-6df9-4ecb-86c8-000000000005"),
                ParentId = Guid.Parse("c3c1384e-9822-49f1-97c5-0d065426329b"),
                SectionGroup = SectionGroupEnum.Step,
                Visibility = SectionVisibilityEnum.Public,
                SectionType = SectionTypeEnum.None,
                Name = "Step5",
                DisplayTitle = "Step 5",
                Help ="this is step 5",
                URI = "-",
                Command = "-",
                IsRequired = true,
                RequiredPolicy = "-",
                Order = 5,
                Gender = GenderEnum.Female,
            },
            new Section {//Parent : PregnancyTest
                Id=Guid.Parse("00000006-6df9-4ecb-86c8-000000000006"),
                ParentId = Guid.Parse("c3c1384e-9822-49f1-97c5-0d065426329b"),
                SectionGroup = SectionGroupEnum.Step,
                Visibility = SectionVisibilityEnum.Public,
                SectionType = SectionTypeEnum.None,
                Name = "Step6",
                DisplayTitle = "Step 6",
                Help ="this is step 6",
                URI = "-",
                Command = "-",
                IsRequired = true,
                RequiredPolicy = "-",
                Order = 6,
                Gender = GenderEnum.Female,
            },
            new Section {//Parent : PregnancyTest
                Id=Guid.Parse("00000007-6df9-4ecb-86c8-000000000007"),
                ParentId = Guid.Parse("c3c1384e-9822-49f1-97c5-0d065426329b"),
                SectionGroup = SectionGroupEnum.Step,
                Visibility = SectionVisibilityEnum.Public,
                SectionType = SectionTypeEnum.None,
                Name = "Step7",
                DisplayTitle = "Step 7",
                Help ="this is step 7",
                URI = "-",
                Command = "-",
                IsRequired = true,
                RequiredPolicy = "-",
                Order = 7,
                Gender = GenderEnum.Female,
            },
            new Section {//Parent : PregnancyTest
                Id=Guid.Parse("00000008-6df9-4ecb-86c8-000000000008"),
                ParentId = Guid.Parse("c3c1384e-9822-49f1-97c5-0d065426329b"),
                SectionGroup = SectionGroupEnum.Step,
                Visibility = SectionVisibilityEnum.Public,
                SectionType = SectionTypeEnum.None,
                Name = "Step8",
                DisplayTitle = "Step 8",
                Help ="this is step 8",
                URI = "-",
                Command = "-",
                IsRequired = true,
                RequiredPolicy = "-",
                Order = 8,
                Gender = GenderEnum.Female,
            },
            new Section {//Parent : PregnancyTest
                Id=Guid.Parse("00000009-6df9-4ecb-86c8-000000000009"),
                ParentId = Guid.Parse("c3c1384e-9822-49f1-97c5-0d065426329b"),
                SectionGroup = SectionGroupEnum.Step,
                Visibility = SectionVisibilityEnum.Public,
                SectionType = SectionTypeEnum.None,
                Name = "Step9",
                DisplayTitle = "Step 9",
                Help ="this is step 9",
                URI = "-",
                Command = "-",
                IsRequired = true,
                RequiredPolicy = "-",
                Order = 9,
                Gender = GenderEnum.Female,
            },
            new Section {//Parent : PregnancyTest
                Id=Guid.Parse("00000010-6df9-4ecb-86c8-000000000010"),
                ParentId = Guid.Parse("c3c1384e-9822-49f1-97c5-0d065426329b"),
                SectionGroup = SectionGroupEnum.Step,
                Visibility = SectionVisibilityEnum.Public,
                SectionType = SectionTypeEnum.None,
                Name = "Step10",
                DisplayTitle = "Step 10",
                Help ="this is step 10",
                URI = "-",
                Command = "-",
                IsRequired = true,
                RequiredPolicy = "-",
                Order = 10,
                Gender = GenderEnum.Female,
            },
            new Section {//Parent : PregnancyTest
                Id=Guid.Parse("00000011-6df9-4ecb-86c8-000000000011"),
                ParentId = Guid.Parse("c3c1384e-9822-49f1-97c5-0d065426329b"),
                SectionGroup = SectionGroupEnum.Step,
                Visibility = SectionVisibilityEnum.Public,
                SectionType = SectionTypeEnum.None,
                Name = "Step11",
                DisplayTitle = "Step 11",
                Help ="this is step 11",
                URI = "-",
                Command = "-",
                IsRequired = true,
                RequiredPolicy = "-",
                Order = 11,
                Gender = GenderEnum.Female,
            },
            new Section {//Parent : step1
                Id=Guid.NewGuid(),
                ParentId = Guid.Parse("00000001-6df9-4ecb-86c8-000000000001"),
                SectionGroup = SectionGroupEnum.Workflow,
                Visibility = SectionVisibilityEnum.Public,
                SectionType = SectionTypeEnum.DemographicInfo,
                Name = "DemographicIntake",
                DisplayTitle = "Demographic Intake",
                Help ="In this section, the corresponding form is filled by the client.",
                URI = "DemographicIntake",
                Command = "Fill Demographic Intake",
                IsRequired = true,
                RequiredPolicy = AppPermissions.PregnancyTest.Demographic,
                Order = 1,
                Gender = GenderEnum.Female,
            },
              new Section {//Parent : step1
                Id=Guid.NewGuid(),
                ParentId = Guid.Parse("00000001-6df9-4ecb-86c8-000000000001"),
                SectionGroup = SectionGroupEnum.Workflow,
                Visibility = SectionVisibilityEnum.Public,
                SectionType = SectionTypeEnum.MedicalInfo,
                Name = "MedicalInfo",
                DisplayTitle = "Medical Info",
                Help ="In this section, the corresponding form is filled by the client.",
                URI = "-",
                Command = "Fill Medical Info",
                IsRequired = true,
                RequiredPolicy = AppPermissions.PregnancyTest.Medical,
                Order = 2,
                Gender = GenderEnum.Female,
            },
            new Section {//Parent : step2
                Id=Guid.NewGuid(),
                ParentId = Guid.Parse("00000002-6df9-4ecb-86c8-000000000002"),
                SectionGroup = SectionGroupEnum.Workflow,
                Visibility = SectionVisibilityEnum.Public,
                SectionType = SectionTypeEnum.CheckIn,
                Name = "CheckIn",
                DisplayTitle = "Check-In",
                Help ="In this section,the check-in will be done by the institution.",
                URI = "CheckIn",
                Command = "CheckIn",
                IsRequired = true,
                RequiredPolicy = AppPermissions.Global.CheckIn,
                Order = 1,
                Gender = GenderEnum.Female,
            },
            new Section {//Parent : step3
                Id=Guid.NewGuid(),
                ParentId = Guid.Parse("00000003-6df9-4ecb-86c8-000000000003"),
                SectionGroup = SectionGroupEnum.Workflow,
                Visibility = SectionVisibilityEnum.Public,
                SectionType = SectionTypeEnum.QaAssignment,
                Name = "QaAssignment",
                DisplayTitle = "Qualified Advocate Assignment",
                Help ="In this section, one of the institution's employees will be responsible for continuing the work.",
                URI = "QaAssignment",
                Command = "Take Client",
                IsRequired = true,
                RequiredPolicy = AppPermissions.PregnancyTest.QaAssignment,
                Order = 1,
                Gender = GenderEnum.Female,
            },
            new Section {//Parent : step4
                Id=Guid.NewGuid(),
                ParentId = Guid.Parse("00000004-6df9-4ecb-86c8-000000000004"),
                SectionGroup = SectionGroupEnum.Workflow,
                Visibility = SectionVisibilityEnum.Public,
                SectionType = SectionTypeEnum.Social,
                Name = "Social",
                DisplayTitle = "Social Form",
                Help ="In this section, the corresponding form is filled by the client.",
                URI = "Social",
                Command = "Fill Social",
                IsRequired = true,
                RequiredPolicy = AppPermissions.PregnancyTest.Social,
                Order = 1,
                Gender = GenderEnum.Female,
            },
            new Section {//Parent : step4
                Id=Guid.NewGuid(),
                ParentId = Guid.Parse("00000004-6df9-4ecb-86c8-000000000004"),
                SectionGroup = SectionGroupEnum.Workflow,
                Visibility = SectionVisibilityEnum.Public,
                SectionType = SectionTypeEnum.TestResult,
                Name = "TestResult",
                DisplayTitle = "Test Result",
                Help ="In this section,the test result will be done by the institution.",
                URI = "TestResult",
                Command = "Fill Test Result",
                IsRequired = true,
                RequiredPolicy = AppPermissions.PregnancyTest.TestResult,
                Order = 2,
                Gender = GenderEnum.Female,
            },
            new Section {//Parent : step5
                Id=Guid.NewGuid(),
                ParentId = Guid.Parse("00000005-6df9-4ecb-86c8-000000000005"),
                SectionGroup = SectionGroupEnum.Workflow,
                Visibility = SectionVisibilityEnum.Public,
                SectionType = SectionTypeEnum.PaAssignment,
                Name = "PaAssignment",
                DisplayTitle = "Pro Advocate Assignment",
                Help ="In this section, one of the institution's employees will be responsible for continuing the work.",
                URI = "PaAssignment",
                Command = "Take Client",
                IsRequired = true,
                RequiredPolicy = AppPermissions.PregnancyTest.PaAssignment,
                Order = 1,
                Gender = GenderEnum.Female,
            },
            new Section {//Parent : step6
                Id=Guid.NewGuid(),
                ParentId = Guid.Parse("00000006-6df9-4ecb-86c8-000000000006"),
                SectionGroup = SectionGroupEnum.Workflow,
                Visibility = SectionVisibilityEnum.Public,
                SectionType = SectionTypeEnum.SocialReview,
                Name = "SocialReview",
                DisplayTitle = "Social Review",
                Help ="In this section, the social form filled by the client is approved by the institution.",
                URI = "Social",
                Command = "Review",
                IsRequired = true,
                RequiredPolicy = AppPermissions.PregnancyTest.SocialReview,
                Order = 1,
                Gender = GenderEnum.Female,
            },
            new Section {//Parent : step7
                Id=Guid.NewGuid(),
                ParentId = Guid.Parse("00000007-6df9-4ecb-86c8-000000000007"),
                SectionGroup = SectionGroupEnum.Workflow,
                Visibility = SectionVisibilityEnum.Public,
                SectionType = SectionTypeEnum.Decision,
                Name = "Decision",
                DisplayTitle = "Decision",
                Help ="In this section, the corresponding form is filled by the client.",
                URI = "Decision",
                Command = "Fill Decision",
                IsRequired = true,
                RequiredPolicy = AppPermissions.PregnancyTest.Decision,
                Order = 1,
                Gender = GenderEnum.Female,
            },
            new Section {//Parent : step8
                Id=Guid.NewGuid(),
                ParentId = Guid.Parse("00000008-6df9-4ecb-86c8-000000000008"),
                SectionGroup = SectionGroupEnum.Workflow,
                Visibility = SectionVisibilityEnum.Public,
                SectionType = SectionTypeEnum.DecisionReview,
                Name = "DecisionReview",
                DisplayTitle = "Decision Review",
                Help ="In this section, the decision form filled by the client is approved by the institution.",
                URI = "Decision",
                Command = "Review",
                IsRequired = true,
                RequiredPolicy = AppPermissions.PregnancyTest.Decision,
                Order = 1,
                Gender = GenderEnum.Female,
            },
            new Section {//Parent : step9
                Id=Guid.NewGuid(),
                ParentId = Guid.Parse("00000009-6df9-4ecb-86c8-000000000009"),
                SectionGroup = SectionGroupEnum.Workflow,
                Visibility = SectionVisibilityEnum.Public,
                SectionType = SectionTypeEnum.Vulnerability,
                Name = "vulnerability",
                DisplayTitle = "Vulnerability",
                Help ="In this section, the vulnerability form filled by the institution.",
                URI = "vulnerability",
                Command = "Fill Vulnerability",
                IsRequired = true,
                RequiredPolicy = AppPermissions.PregnancyTest.Vulnerability,
                Order = 1,
                Gender = GenderEnum.Female,
            },
            new Section {//Parent : step10
                Id=Guid.NewGuid(),
                ParentId = Guid.Parse("00000010-6df9-4ecb-86c8-000000000010"),
                SectionGroup = SectionGroupEnum.Workflow,
                Visibility = SectionVisibilityEnum.Public,
                SectionType = SectionTypeEnum.ExitSurvey,
                Name = "ExitSurvey",
                DisplayTitle = "Exit Survey",
                Help ="In this section, the exit survey form filled by the institution.",
                URI = "ExitSurvey",
                Command = "Fill Survey",
                IsRequired = true,
                RequiredPolicy = AppPermissions.PregnancyTest.ExitSurvey,
                Order = 1,
                Gender = GenderEnum.Female,
            },
            new Section {//Parent : step10
                Id=Guid.NewGuid(),
                ParentId = Guid.Parse("00000010-6df9-4ecb-86c8-000000000010"),
                SectionGroup = SectionGroupEnum.Workflow,
                Visibility = SectionVisibilityEnum.Public,
                SectionType = SectionTypeEnum.ARL,
                Name = "ARL",
                DisplayTitle = "ARL",
                Help ="In this section, the ARL form filled by the institution.",
                URI = "ARL",
                Command = "ARL",
                IsRequired = true,
                RequiredPolicy = AppPermissions.PregnancyTest.RequestList,
                Order = 2,
                Gender = GenderEnum.Female,
            },
            new Section {//Parent : step11
                Id=Guid.NewGuid(),
                ParentId = Guid.Parse("00000011-6df9-4ecb-86c8-000000000011"),
                SectionGroup = SectionGroupEnum.Workflow,
                Visibility = SectionVisibilityEnum.Public,
                SectionType = SectionTypeEnum.Spiritual,
                Name = "Spiritual",
                DisplayTitle = "Spiritual Form",
                Help ="In this section, the ARL form filled by the institution.",
                URI = "Spiritual",
                Command = "Fill Spiritual",
                IsRequired = false,
                RequiredPolicy = AppPermissions.PregnancyTest.Spiritual,
                Order = 1,
                Gender = GenderEnum.Female,
            },
            new Section {//Parent : step11
                Id=Guid.NewGuid(),
                ParentId = Guid.Parse("00000011-6df9-4ecb-86c8-000000000011"),
                SectionGroup = SectionGroupEnum.Workflow,
                Visibility = SectionVisibilityEnum.Public,
                SectionType = SectionTypeEnum.CheckOut,
                Name = "Checkout",
                DisplayTitle = "Check-out",
                Help ="In this section,the check-out will be done by the institution.",
                URI = "Checkout",
                Command = "Check-out",
                IsRequired = false,
                RequiredPolicy = AppPermissions.Global.Checkout,
                Order = 2,
                Gender = GenderEnum.Female,
            },
        };
    }
}